apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mdbm-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mdbm-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
