apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mdbm-operator.fullname" . }}-webhook-server-cert
  annotations:
    simplecert.samsung.com/dns-names: {{ include "mdbm-operator.fullname" . }}.{{ .Release.Namespace }}.svc,{{ include "mdbm-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    simplecert.samsung.com/add-ca-to-secret: "false"
    simplecert.samsung.com/validating-webhook-name: "{{ include "mdbm-operator.fullname" . }}-{{ .Release.Namespace }}-validating-webhook-configuration"
    simplecert.samsung.com/cert-lifetime: ""
    simplecert.samsung.com/ca-lifetime: ""
type: kubernetes.io/tls
data:
  tls.crt:  Cg==
  tls.key:  Cg==
