kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simplecert-clusterrole-{{ .Release.Namespace }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
