apiVersion: v1
kind: Service
metadata:
  name: {{ include "mdbm-api.fullname" . }}
  labels:
{{ include "mdbm-api.labels" . | indent 4 }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  {{ if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
      protocol: TCP
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "mdbm-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ipFamilies }}
  ipFamilies:
{{ toYaml . | indent 4 }}
  {{- end }}
  ipFamilyPolicy: {{ .Values.ipFamilyPolicy }}
