apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mdbm.pmm.fullname" . }}
data:
  username: {{ .Values.global.pmm.username | b64enc | quote}}
  password: {{ .Values.global.pmm.password | b64enc | quote}}
