apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mdbm-operator-metric-rolebinding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mdbm-operator-metrics-reader-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: mdbm-operator-metrics-reader
  namespace: {{ .Release.Namespace }}
{{ if .Values.global.openshift }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-scc-privileged-metrics-reader
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: mdbm-operator-metrics-reader
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-scc-anyuid-metrics-reader
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: mdbm-operator-metrics-reader
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
{{ end }}

