{{- if .Values.global.registries.registry1.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.registries.registry1.imagePullSecret.name}}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.registries.registry1.imagePullSecret.encodedsecret}}
{{- end }}
