name: Integration Tests
on: pull_request
jobs:
  go-tests:
    name: Run Charts Integration Tests
    runs-on: code-default
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 0.12.21
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Create k8s Kind Cluster
        run: go get sigs.k8s.io/kind && kind create cluster --image kindest/node:latest
      - name: Run Go Tests
        working-directory: test
        run: go test -v -tags=integration
        env:
          ACK_GINKGO_DEPRECATIONS: "2.1.4"
